### ISSUE TITLE
Missing members in FusedLocationProviderClient

### ISSUE THREAD

**Issue by johnthiriet** [omernaser/Huawei-Location#1]
Hello,

First thanks for your work I was going to try binding the Maps and Location SDK myself but then i found your nuget packages.

Unfortunately there are some errors when trying to use the FusedLocationProviderClient. Most of the members are missing.

To reproduce, download your sample and try to compile.

Maybe the package is not up to date on Nuget ?

Also, I did not find the source code of the binding and that would be better to help fixing issues. So if you have some time please indicate me the git repo where I can find them.

Kind regards,

**Comment by omernaser** [comment]
can you please check again i download the sample and it's working fine 
![image](https://user-images.githubusercontent.com/13206366/86116375-ffc32180-bad5-11ea-8a9b-2d41a94c2a5e.png)

**Comment by johnthiriet** [comment]
Hi.

Did check again and confirm my results.


<img width="1676" alt="image" src="https://user-images.githubusercontent.com/10599907/86201850-e7e4af80-bb60-11ea-88b3-824ca2423e33.png">

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/10599907/86201984-53c71800-bb61-11ea-8e02-ce6cbd51b5dc.png">

**Comment by johnthiriet** [comment]
Hi @omernaser. Did you have the chance to take a look at this. I tried doing the binding myself but I stumble on the same issues that you did here : [https://github.com/xamarin/xamarin-android/issues/4379#issuecomment-614540009](https://github.com/xamarin/xamarin-android/issues/4379#issuecomment-614540009)

I am struggling to see how you overcame these issues as it is a blocking point for us.

**Comment by johnthiriet** [comment]
Hi @omernaser.

Just for your info, I redid all the bindings and made them public as it was really blocking us.
Nuget packages are also available.

Bindings
[https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms](https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms).

Demo
[https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms.Demo](https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms.Demo)

**Comment by filipoff2** [comment]
Hmm I'm doing analytics 
but I don't understand why they haven't done nugget from it ? 
Why those jars and  are not included by default in sample project?

**Comment by filipoff2** [comment]
From support I got answer  that code  references should looks as:

+--- com.huawei.hms:hianalytics:5.0.1.301
|  +--- com.huawei.agconnect:agconnect-core:1.3.0.300 -> 1.4.0.300
|  |  \--- com.huawei.hmf:tasks:1.3.3.300 -> 1.4.1.300
|  +--- com.huawei.agconnect:agconnect-credential:1.3.0.300
|  |  +--- com.huawei.hmf:tasks:1.3.3.300 -> 1.4.1.300
|  |  +--- com.huawei.agconnect:agconnect-core:1.3.0.300 -> 1.4.0.300 (*)
|  |  +--- com.squareup.okhttp3:okhttp:3.11.0
|  |  |  \--- com.squareup.okio:okio:1.14.0
|  |  +--- com.huawei.agconnect:agconnect-https:1.3.0.300
|  |  |  +--- com.squareup.okhttp3:okhttp:3.11.0 (*)
|  |  |  \--- com.huawei.hmf:tasks:1.3.3.300 -> 1.4.1.300
|  |  +--- com.huawei.agconnect:datastore-annotation:1.3.0.300
|  |  \--- com.huawei.agconnect:datastore-core:1.3.0.300
|  |     \--- com.huawei.agconnect:datastore-annotation:1.3.0.300
|  +--- com.huawei.hms:opendevice:5.0.0.300
|  |  \--- com.huawei.hms:base:4.0.4.300 -> 5.0.0.301
|  |     +--- com.huawei.hms:availableupdate:5.0.0.301
|  |     |  +--- com.huawei.hms:ui:5.0.0.301
|  |     |  |  \--- com.huawei.hms:log:5.0.0.301
|  |     |  +--- com.huawei.hms:stats:5.0.0.301
|  |     |  |  +--- com.huawei.hms:network-grs:4.0.2.300
|  |     |  |  |  \--- com.huawei.hms:network-common:4.0.2.300
|  |     |  |  \--- com.huawei.hms:log:5.0.0.301
|  |     |  +--- com.huawei.hms:device:5.0.0.301
|  |     |  |  +--- com.huawei.hms:log:5.0.0.301
|  |     |  |  \--- com.huawei.agconnect:agconnect-core:1.4.0.300 (*)
|  |     |  +--- com.huawei.hms:log:5.0.0.301
|  |     |  \--- com.huawei.hms:update:2.0.6.302
|  |     |     \--- com.huawei.hms:network-grs:4.0.2.300 (*)
|  |     +--- com.huawei.hms:stats:5.0.0.301 (*)
|  |     +--- com.huawei.hms:ui:5.0.0.301 (*)
|  |     +--- com.huawei.hms:device:5.0.0.301 (*)
|  |     +--- com.huawei.hms:log:5.0.0.301
|  |     \--- com.huawei.hmf:tasks:1.4.1.300
|  \--- com.huawei.hms:base:5.0.0.301 (*)

Question to @johnthiriet  do you have reference  to **com.squareup.okhttp3:okhttp:3.11.0** in your project or it works fine without it? 

|  |  +--- com.huawei.agconnect:agconnect-https:1.3.0.300
**|  |  |  +--- com.squareup.okhttp3:okhttp:3.11.0 (*)**
|  |  |  \--- com.huawei.hmf:tasks:1.3.3.300 -> 1.4.1.300

**Comment by johnthiriet** [comment]
Hi @filipoff2 
I just finished binding ScanKit and you can find every binding there [https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms](https://github.com/johnthiriet/Xamarin.Android.Huawei.Hms).
I did not have the need to bind Analytics Kit for the moment and it seems that OkHttp was not required for the other Kits I have bound.
The Huawei documentations gives a few hint for Analytics Kit: [https://developer.huawei.com/consumer/en/doc/development/HMS-Library/hms-analytics-xamarin-sdkdownload](https://developer.huawei.com/consumer/en/doc/development/HMS-Library/hms-analytics-xamarin-sdkdownload)
It states OkHttp should be referenced as a nuget in the AAR that needs it.

This is the state of the binding I have so far that could help you for Analytics Kit.
If you managed to advance in the binding process PR are welcome :)

Library Name | Library Version | Library Download | Already bound
-- | -- | -- | --
HiAnalytics | 4.0.2.300 | hianalytics-4.0.2.300.aar | No
Tasks | 1.3.3.300 | tasks-1.3.3.300.aar | Yes
Update | 2.0.6.300 | update-2.0.6.300.aar | Yes
Network Grs | 4.0.2.300 | network-grs-4.0.2.300.aar | Yes
Network Common | 4.0.2.300 | network-common-4.0.2.300.aar | Yes
Base | 4.0.2.300 | base-4.0.2.300.aar | Yes
Open Device | 4.0.1.301 | opendevice-4.0.1.301.aar | Yes
AgConnect Core | 1.0.0.300 | agconnect-core-1.0.0.300.aar | Yes
AgConnect Credential | 1.0.0.300 | agconnect-credential-1.0.0.300.aar | No
AgConnect Https | 1.0.0.300 | agconnect-https-1.0.0.300.aar | No
DataStore Core | 1.0.0.300 | datastore-core-1.0.0.300.aar | No
DataStore Annotation | 1.0.0.300 | datastore-annotation-1.0.0.300.jar | No
OkHttp3 | 3.11.0 | square.okhttp3.3.11.0 (NuGet) | N/A
OkIO | 1.14.0 | xamarin.square.okio.1.14.0 (NuGet) | N/A

**Comment by johnthiriet** [comment]
@filipoff2 I have done the binding and a sample project.
Everything is working fine for me as long as I do not reference the update.x.x.x.aar files.
You can download the nuget [https://www.nuget.org/packages/Xamarin.Android.Huawei.Hms.HiAnalytics](https://www.nuget.org/packages/Xamarin.Android.Huawei.Hms.HiAnalytics).
Binding source code and sample source code are at the sample places I have stated before.

Kind regards.
